### ISSUE TITLE
goxc

### ISSUE THREAD

**Issue by sundarv85** [attilaolah/box-godep#1]
Hello,

I see you had contributed to the goxc box in wercker.
https://github.com/motemen/wercker-box-golang-goxc/blob/master/wercker-box.yml

I need both goxc and godep in a single box. Would it be possible currently, without creating a new box myself.

Thanks
Sundar

**Comment by attilaolah** [comment]
I think your best option is to use the `goxc` box and `go get -u github.com/tools/godep` inside that.

Or create a box yourself.

---

Alternatively, you could switch your Wercker app to use the Ewok platform, which is docker-based, so you can use multiple Docker images (one main image and other images listed as `services:`). However, to use the other images' file systems, you would have to mount them somehow, and I'm not sure how to do that.

**Comment by attilaolah** [comment]
Please reopen if this does not answer your question.
